---
personal:
  name: David Reay #\\B.Sc. MBA
  first_name: David
  last_name: Reay
  title: AWS Architect | DevOps Engineer
  post_nominals: MBA, BSc
  summary: >
    First-class B. Sc. Honours, and MBA Technology Management Graduate, Agile/SAFe trained, 
    AWS Professional Certified Architect/Engineer with +15 years experience of systems 
    engineering and solutions architecture.
  email: 'david@awsbot.com'
  phone: '+44 (0) 7834 980 889'
  location: London, United Kingdom
  github: https://github.com/awsbot-ltd
  linkedin: davidreay
  website: https://forhire.awsbot.com
  nationality: British
  security_clearance: BPSS (Active)
  interests:
    - title: Backgammon
      description: Love playing and have made a video game.


languages:
  - English (Native)
  - French (Beginner)
  - German (Beginner)
  - Spanish (Beginner)
  - Dutch (Beginner)

achievements:
  - icon: '\faRocket'
    title: 'Achievement 1'
    description: 'Led the successful launch of a financial data integration platform at Plaid, significantly increasing market penetration.'
  - icon: '\faStarHalf*'
    title: 'Achievement 2'
    description: 'Implemented a customer feedback loop at Plaid, improving customer satisfaction scores by 40\%.'
  - icon: '\faStarHalf*'
    title: 'Achievement 3'
    description: 'Implemented a customer feedback loop at Plaid, improving customer satisfaction scores by 40\%.'
  - icon: '\faStarHalf*'
    title: 'Achievement 4'
    description: 'Implemented a customer feedback loop at Plaid, improving customer satisfaction scores by 40\%.'

skill_groups:
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3
  - skill1
  - skill2
  - skill3

experience:
  - company: 'Company 1'
    logo: giacom_logo.jpeg
    location: 'Southampton, UK'
    location_type: 'Remote'
    employment_type: 'Contract'
    position: 'Position 1'
    current: false
    start_date:
      month: 'April'
      year: '2024'
    end_date:
      month: 'February'
      year: '2025'
    description: >
      As a Senior Data Engineer, I was responsible for designing and implementing
      data architecture solutions, building and maintaining data pipelines for a
      team delivering AWS-based data solutions. Skills and experience included:
    achievements:
      - Architected multi-account AWS Landing Zones and VPC segmentation using Terraform.
      - Developed automated CI/CD pipelines for data solutions using Glue and Lambda.
      - Mentored junior staff on DevSecOps best practices and AWS Well-Architected Framework.
    responsibilities:
      - Designing data architecture and maintaining pipelines for AWS-based data solutions.
      - Utilizing Amazon Bedrock and Generative AI (Chat-GPT).
      - Working with AWS data stack (Lambda, Glue, Lake Formation, Athena, EMR).
    skills:
      - 'Terraform'
      - 'AWS Glue'
      - 'Amazon Bedrock'

  - company: 'US Digital Response'
    logo: usdr.jpeg
    location: 'Remote'
    location_type: 'Volunteer'
    employment_type: 'Volunteer'
    position: 'Volunteer Technical Consultant'
    current: true
    start_date:
      month: 'March'
      year: '2024'
    end_date:
      month: 'August'
      year: '2025'
    description: >
      Assisting government agencies in leveraging technology. Currently working with the Arizona Coconino 
      Electoral Office to educate officers on the use of Generative AI for improved decision-making.
    achievements:
      - Conducted workshops and technical training sessions on Generative AI tailored to electoral needs.
      - Identified key areas where AI solutions could enhance office efficiency and effectiveness.
      - Developed and implemented custom AI solutions to address specific administrative challenges.
      - Created comprehensive guides to ensure successful long-term adoption of AI technologies.
    responsibilities:
      - Technical training, project management, and custom AI solution development.
    skills:
      - 'Generative AI'
      - 'Technical Training'
      - 'Stakeholder Management'

  - company: 'TechToTheRescue'
    ogo: techrescue.jpeg
    location: 'Remote'
    location_type: 'Volunteer'
    employment_type: 'Volunteer'
    position: 'Volunteer Developer'
    current: true
    start_date:
      month: 'February'
      year: '2024'
    end_date:
      month: 'August'
      year: '2024'
    description: >
      Collaborating with a charitable organisation to support nonprofits. Currently assisting a Nigerian 
      youth-led social enterprise in digitising an environmental sustainability card game into a mobile application.
    achievements:
      - Designed and developed a 2D card game for Android using Unity and C\#.
      - Led the project from concept to deployment, coordinating with international stakeholders.
      - Conducted thorough testing and optimization for performance and stability on Android devices.
      - Provided comprehensive documentation and training to ensure independent project maintenance.
    responsibilities:
      - Unity 2D game development, C\# programming, and game mechanics design.
      - Facilitating regular meetings and requirement gathering with social enterprise teams.
    skills:
      - 'Unity'
      - 'C\#'
      - 'Android Development'
      - 'Game Design'

  - company: 'Mental Health Innovations UK'
    logo: mental_health_innovations_logo.jpeg
    location: 'London, UK'
    location_type: 'Remote'
    employment_type: 'Contract'
    position: 'Data Engineer'
    current: false
    start_date:
      month: 'May'
      year: '2023'
    end_date:
      month: 'January'
      year: '2024'
    description: 'Contract to develop an existing de-identification data pipeline with pyspark and NLP. Skills and experience included:'
    achievements:
      - Developed an existing de-identification data pipeline with Pyspark and NLP.
      - Performance testing and enhancement with ARM64 AWS Graviton processors.
      - Implemented TDD with pytest, pylint, and OpenAI API.
    responsibilities:
      - Python development with spaCy and spark-nlp for Named Entity Recognition.
      - Infrastructure as Code with CloudFormation and Dockerization with EMR Serverless.

education:
  - degree: MSc Cyber Security
    institution: The Open University
    year: 2025 – 2031
  - degree: MSc Artificial Intelligence
    institution: University of Hertfordshire
    year: 2025 – 2027

certifications_and_training:
  - name: 'Cert 1'
    issuer: 'Amazon Web Services (AWS)'
    category: 'Amazon Web Services (AWS)'
  - name: 'Cert 2'
    issuer: 'Amazon Web Services (AWS)'
    category: 'Amazon Web Services (AWS)'
